{-
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.

[minhuang@mocha:haskell]$ time runghc problem-00002.hs 
4613732

real    0m0.339s
user    0m0.280s
sys     0m0.028s
-}
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
result = sum [x | x <- takeWhile (<4000000) fibs, even x]
main = print result
