(require rackunit/text-ui)
(require "core-tests.rkt")
(require "number-theory-tests.rkt")
(require "set-tests.rkt")

(displayln "core-tests")
(run-tests core-tests)
(displayln "number-theory-tests")
(run-tests number-theory-tests)
(displayln "set-tests")
(run-tests set-tests)
