/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/
import scala.Math._
import scala.Stream._

val phi = (1.0 + sqrt(5.0)) / 2.0
def fib(n: Int) = floor(pow(phi, n) / pow(5.0, .5) + .5)
val result = from(0, 1).map(fib(_))
                       .filter(_ % 2 == 0)
                       .takeWhile(_ <= 4E6)
                       .reduceLeft(_ + _)
println(result)
