name: Build and Test

on:
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
  push:
    branches:
      - main

jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Fix
        run: npm run fix

      - name: Build
        run: npm run build

      - name: Commit
        if: ${{ github.ref != 'refs/heads/main' }}
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@github.com
          message: Automatic commit via GitHub Actions

      - name: Test
        if: ${{ steps.commit.outputs.committed == 'false' }}
        run: npm run test
