name: Python

on:
  pull_request:
    paths:
      - .github/workflows/solns-python.yml
      - solns/python/**
  push:
    paths:
      - .github/workflows/solns-python.yml
      - solns/python/**
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: solns/python
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-vesrion: 3.9.2

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint
