name: Ruby

on:
  pull_request:
    paths:
      - .github/workflows/solns-ruby.yml
      - solns/ruby/**
  push:
    paths:
      - .github/workflows/solns-ruby.yml
      - solns/ruby/**
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: solns/ruby
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint
