name: Haskell

on:
  pull_request:
    paths:
      - .github/workflows/solns-haskell.yml
      - solns/haskell/**
  push:
    paths:
      - .github/workflows/solns-haskell.yml
      - solns/haskell/**
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    # We would use setup-haskell here as installing these tools via cabal is a bit slower, but the setup-haskell action
    # has been archived.
    #
    # See https://github.com/actions/setup-haskell
    container: haskell:8.8.4
    defaults:
      run:
        working-directory: solns/haskell
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint
