name: Golang

on:
  pull_request:
    paths:
      - .github/workflows/solns-golang.yml
      - solns/golang/**
  push:
    paths:
      - .github/workflows/solns-golang.yml
      - solns/golang/**
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: solns/golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>= 1.18.0'

     - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.1
