name: Ruby

on:
  pull_request:
    paths:
      - .github/workflows/solns-ruby.yml
      - solns/ruby/**
  push:
    paths:
      - .github/workflows/solns-ruby.yml
      - solns/ruby/**
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    container: ruby:3.1.2-slim
    defaults:
      run:
        working-directory: solns/ruby
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bundle install

      - name: Lint
        run: rubocop
